<?php

namespace Nemundo\Content\App\Widget\Content\UniqueId;

use Nemundo\Content\Type\AbstractContentBuilder;

class UniqueIdWidgetBuilder extends AbstractContentBuilder
{

    protected function loadBuilder()
    {

        // TODO: Implement loadBuilder() method.
        $this->contentType=new UniqueIdType();
    }


    protected function onCreate()
    {
        //parent::onCreate(); // TODO: Change the autogenerated stub


        $this->dataId=0;


    }


}