<?php

namespace Nemundo\Content\App\Feed\Com\Container;

use Nemundo\Html\Block\Div;

class FeedContainer extends Div
{

    public function getContent()
    {



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}