<?php

namespace Nemundo\Content\App\Timeline\Action;

use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Admin\Com\Table\Row\AdminTableRow;
use Nemundo\Content\Action\AbstractActionView;
use Nemundo\Content\App\Timeline\Data\Timeline\TimelineReader;

class TimelineActionView extends AbstractActionView
{

    public function getContent()
    {

        $table=new AdminTable($this);

        $reader = new TimelineReader();
        $reader->filter->andEqual($reader->model->contentId,$this->contentId);
        foreach ($reader->getData() as $timelineRow) {

            $row=new AdminTableRow($table);
            $row->addText($timelineRow->date->getShortDateFormat());


        }




        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}